# Generated by Django 5.2.17 on 2026-10-01 20:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CharacterVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField()),
                ("name", models.CharField(max_length=100)),
                (
                    "rarity",
                    models.CharField(
                        choices=[("common", "Common"), ("rare", "Rare"), ("epic", "Epic")],
                        default="common",
                        max_length=10,
                    ),
                ),
                ("asset_key", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "code"), name="variant_character_code_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rarity__in", ["common", "rare", "epic"])),
                        name="variant_rarity_valid",
                    ),
                ],
            },
        ),
    ]
